# application.yml - Database Performance Configuration

spring:
  # Database Configuration
  datasource:
    hikari:
      # Connection Pool Settings
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      leak-detection-threshold: 60000

      # Performance Monitoring
      register-mbeans: true

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        generate_statistics: false

# Logging Configuration for Performance Analysis
logging:
  level:
    # Database Queries
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.loader.Loader: DEBUG
    org.hibernate.engine.loading.internal.LoadContexts: DEBUG
    org.hibernate.stat: DEBUG

    # Connection Pool
    com.zaxxer.hikari: DEBUG

    # Your Application
    com.gws.crm: INFO

    # Performance Monitors
    com.gws.crm.common.authentication.aspects.DatabasePerformanceMonitor: INFO
    com.gws.crm.common.filters.PerformanceAnalysisFilter: INFO

# Server Configuration
server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
    max-connections: 8192
    connection-timeout: 20000

# Management Endpoints for Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,hikaricp,loggers
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true

# Custom Application Properties
app:
  monitoring:
    enabled: true
    slow-query-threshold: 500ms
    log-all-queries: false