package com.gws.crm.authentication.constants;

public enum SpecificRole {
    ACCOUNTANT,
    BRANCH_MANAGER,
    CALL_CENTER_AGENT,
    CUSTOMER_SERVICE_AGENT,
    CUSTOMER_SERVICE_MANAGEMENT,
    CUSTOMER_SERVICE_TEAM_LEADER,
    DATA_ENTRY,
    MARKETING,
    MARKETING_MANAGER,
    QUALITY_CONTROL,
    SALES_ADMIN,
    SALES_DIRECTOR,
    SALES_MANAGER,
    SALES_REP,
    TEAM_LEADER,
    TELESales_AGENT,
    TELESales_LEADER
}
