name: Build & Deploy to Tomcat

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build WAR
        run: mvn -B -DskipTests package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-war
          path: target/*.war

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download WAR
        uses: actions/download-artifact@v4
        with:
          name: app-war
          path: .

      - name: Pick WAR filename
        id: war
        run: echo "WAR=$(ls *.war | head -n1)" >> $GITHUB_OUTPUT

      - name: Deploy via Tomcat Manager
        env:
          TOMCAT_URL: ${{ secrets.TOMCAT_URL }}
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        run: |
          # Update (or create) deployment at /CRM
          curl -sS --fail -u "$TOMCAT_USER:$TOMCAT_PASSWORD" \
            -T "${{ steps.war.outputs.WAR }}" \
            "$TOMCAT_URL/manager/text/deploy?path=/CRM&update=true"
          echo "Deployed as /CRM"

      - name: Smoke check (optional but recommended)
        if: ${{ secrets.APP_HEALTH_URL != '' }}
        env:
          APP_HEALTH_URL: ${{ secrets.APP_HEALTH_URL }}
        run: |
          sleep 5
          curl -sS --fail "$APP_HEALTH_URL" | tee /dev/stdout
